name: py27msbparc

channels:
- anaconda
- conda-forge
- aramislab
- defaults

dependencies:
- python=2.7.15
- pip=19.0.3
- ants=2.2.0
- numpy=1.15.4
- matplotlib=2.2.3
- graphviz=2.40.1
- traits=5.1.1
- nipype=1.1.8

- pip:
    - duecredit==0.7.0
    - apptools==4.4.0
    - networkx==2.2
    - sphinx==1.5.1
    - sphinx_rtd_theme==0.4.3
    - sphinx-argparse==0.2.5
    - recommonmark==0.5.0
    - pybids==0.9.1
