
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      # - run:
      #     name: verify git tag vs. version
      #     command: |
      #       python -m venv venv
      #       . venv/bin/activate
      #       python setup.py verify
      # - run:
      #     name: init .pypirc
      #     command: |
      #       echo -e "[pypi]" >> ~/.pypirc
      #       echo -e "username = madhurt" >> ~/.pypirc
      #       echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      # - run:
      #     name: create packages
      #     command: |
      #       python3 setup.py sdist
      #       python3 setup.py bdist_wheel
      # - run:
      #     name: upload to pypi
      #     command: |
      #       . venv/bin/activate
      #       twine upload dist/*
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin
      - run:
          name: Build and push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t sebastientourbier/multiscalebrainparcellator:latest -t sebastientourbier/multiscalebrainparcellator:$CIRCLE_TAG .
            docker push sebastientourbier/multiscalebrainparcellator:latest
            docker push sebastientourbier/multiscalebrainparcellator:$CIRCLE_TAG
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              only:
                -master
